---
name: lint
on:
  workflow_dispatch:
  push:
    # Run superlinter on pushes to default branch
    branches:
      - main
  # Run superlinter on pull request events
  pull_request_target:

# Declare default permissions as read-only
permissions: read-all

jobs:
  super-linter:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: ðŸ”’ harden runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: ðŸ§¹ run superlinter
        uses: super-linter/super-linter@85f7611e0f7b53c8573cca84aa0ed4344f6f6a4d # v7.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: "."
          YAML_CONFIG_FILE: ".yamllint"
          CHECKOV_FILE_NAME: ".checkov.yaml"
          DOCKERFILE_HADOLINT_FILE_NAME: ".hadolint.yaml"
          VALIDATE_GIT_COMMITLINT: false
          VALIDATE_ALL_CODEBASE: false
          # Reenable when java service is modernized
          VALIDATE_JAVA: false
          # Reenable when Node.JS service is modernized
          VALIDATE_JAVASCRIPT_STANDARD: false
          # We want to remove the PHP script for the mysql database later, so
          # we disable php linting for now
          VALIDATE_PHP_PHPCS: false
          VALIDATE_PHP_PSALM: false
          # jscpd reports a lot of false positives on sample files but the configuration is broken,
          # so we keep it disabled for now.
          VALIDATE_JSCPD: false
          # We disable pylint and flake8 for now. The python code still needs to be fixed for them.
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_RUFF: false
          # Checkov is behaving strangely right now, disable it and renable it later
          VALIDATE_CHECKOV: false
          MULTI_STATUS: false
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
