---
on:
  workflow_call:
    inputs:
      push:
        description: Set to true to push images to registries
        default: false
        required: false
        type: boolean
      registry_ghcr:
        description: github container registry
        default: "ghcr.io/cisco-open/app-simulator"
        required: false
        type: string

# Declare default permissions as read-only
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        image:
          - context: ./src/loaders/curl
            name: loaders-curl
          - context: ./src/services/java
            name: services-java
          - context: ./src/services/nodejs
            name: services-nodejs
          - context: ./src/databases/mysql
            name: databases-mysql
          - context: ./scripts/generators/docker-compose
            name: generators-docker-compose
          - context: ./scripts/generators/k8s
            name: generators-k8s
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry_ghcr }}-${{ matrix.image.name }} # e.g. ghcr.io/cisco-open/app-simulator-loaders-curl
          # build nightly releases on schedule
          # build semver releases on tag
          # build edge releases on main branch
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
            type=semver,pattern={{ version }}
            type=edge,branch=main
          labels: |

      - name: Log into GitHub Container Registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: cisco-service
          password: ${{ secrets.PACKAGE_PUBLICATION_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64, amd64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image.context }}
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.push }}
          cache-from: type=gha
          cache-to: type=gha
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
